# pandas

In [2]:
import os

os.makedirs(os.path.join("..", "data"), exist_ok=True)

In [3]:
data_file = os.path.join("..", "data", "house_tiny.csv")

In [8]:
with open(data_file, "w") as f:
    f.write("numRooms,Alley,Price\n")
    f.write("NA,price,127500\n")
    f.write("2,NA,10600\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,14000\n")

In [10]:
import pandas as pd

In [11]:
import numpy as np

# 创建数组
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# 保存为.npy文件
np.save('array.npy', arr)

In [12]:
data = pd.read_csv(data_file)
print(data)

   numRooms  Alley   Price
0       NaN  price  127500
1       2.0    NaN   10600
2       4.0    NaN  178100
3       NaN    NaN   14000


In [15]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:,2]
print(inputs,"\n\n", outputs)

   numRooms  Alley
0       NaN  price
1       2.0    NaN
2       4.0    NaN
3       NaN    NaN 

 0    127500
1     10600
2    178100
3     14000
Name: Price, dtype: int64


In [28]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# 修改这行：使用正确的 pandas 索引方式
inputs['numRooms'] = inputs['numRooms'].fillna(inputs['numRooms'].mean())
print(inputs)

   numRooms  Alley
0       3.0  price
1       2.0    NaN
2       4.0    NaN
3       3.0    NaN


In [29]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   numRooms  Alley_price  Alley_nan
0       3.0         True      False
1       2.0        False       True
2       4.0        False       True
3       3.0        False       True


In [30]:
import tensorflow as tf
X = tf.constant(inputs.to_numpy(dtype=float))

In [31]:
y = tf.constant(outputs.to_numpy(dtype=float))

In [32]:
X,y

(<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
 array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]])>,
 <tf.Tensor: shape=(4,), dtype=float64, numpy=array([127500.,  10600., 178100.,  14000.])>)

In [45]:
data = pd.read_csv(data_file)

In [38]:
for column in data.columns:
    print(f"Column name: {column}")
    print(data[column])

Column name: numRooms
0    NaN
1    2.0
2    4.0
3    NaN
Name: numRooms, dtype: float64
Column name: Alley
0    price
1      NaN
2      NaN
3      NaN
Name: Alley, dtype: object
Column name: Price
0    127500
1     10600
2    178100
3     14000
Name: Price, dtype: int64


In [51]:
tmp_data = {}
for item, data1 in data.items():
    count = 0
    for t, d in data1.items():
        # 判断是不是na
        if pd.isna(d):
            count += 1
    tmp_data[item] = count

print(tmp_data)

{'numRooms': 2, 'Alley': 3, 'Price': 0}


In [57]:
max_value = max(tmp_data.values())
print(max_value)
# 根据max_value获取列名
max_key = max(tmp_data, key=tmp_data.get)
print(max_key)

3
Alley


In [58]:
data.drop(columns=max_key, inplace=True)
print(data)

   numRooms   Price
0       NaN  127500
1       2.0   10600
2       4.0  178100


In [59]:
t_t = tf.constant(data.to_numpy(), dtype=tf.float32)
print(t_t)

tf.Tensor(
[[      nan 1.275e+05]
 [2.000e+00 1.060e+04]
 [4.000e+00 1.781e+05]], shape=(3, 2), dtype=float32)
