# 数据操作

In [2]:
import tensorflow as tf

In [4]:
x = tf.range(12)
x.shape

TensorShape([12])

In [5]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
x = tf.reshape(x, (4,3))

In [8]:
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [9]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [10]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [11]:
tf.random.normal(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.5583387 , -0.12910604, -1.1686467 , -0.82112676],
       [ 0.9743943 , -1.2778778 , -0.184232  ,  0.951506  ],
       [-1.8130933 , -0.03175124, -2.011952  , -0.9749709 ]],
      dtype=float32)>

In [12]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [21]:
x = tf.constant([1.0,2,4,8])
y = tf.constant([2.0,2,2,2])
x+y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>

In [22]:
x*y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>

In [23]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809578e+03],
      dtype=float32)>

In [26]:
tf.matmul(tf.reshape(x,[1,4]), tf.reshape(y,[4,1]))


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[30.]], dtype=float32)>

In [3]:
X= tf.reshape(tf.range(12, dtype=tf.float32), (3,4))
Y =tf.constant([[2.0, 1, 4,3], [1, 2, 3, 4], [4, 3, 2, 1]])

tf.concat([X, Y], axis = 0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 2.,  1.,  4.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.]], dtype=float32)>

In [4]:
tf.concat([X, Y], axis = 1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>

In [5]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [6]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>