# 线性代数

In [2]:
import tensorflow as tf
x = tf.constant(3.0)
y = tf.constant(4.0)
print(x)
print(y)

print(x+y)
print(x*y)
print(x/y)
print(x**y)


tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(0.75, shape=(), dtype=float32)
tf.Tensor(81.0, shape=(), dtype=float32)


In [3]:
x = tf.range(10)
print(x)



tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [4]:
x[2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
len(x)

10

In [6]:
x.shape

TensorShape([10])

In [8]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
print(x.shape)
len(x)


[1 2 3 4 5]
(5,)


5

In [9]:
A = tf.reshape(tf.range(20), (5,4))
print(A)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)


In [10]:
print(A[2][3])

tf.Tensor(11, shape=(), dtype=int32)


In [12]:
AT = tf.transpose(A)
print(AT)

tf.Tensor(
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]], shape=(4, 5), dtype=int32)


In [13]:
B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B)

B == tf.transpose(B)

tf.Tensor(
[[1 2 3]
 [2 0 4]
 [3 4 5]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [14]:
X = tf.reshape(tf.range(24), (2,3,4))
print(X)


tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [15]:
A = tf.reshape(tf.range(20), (5,4))
B =A

In [16]:
id(A) == id(B)

True

In [17]:
A, A+B

(<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=int32)>,
 <tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]], dtype=int32)>)

In [18]:
A*B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]], dtype=int32)>

In [24]:
# tf.matmul(A, B)

a =2 
B = tf.reshape(tf.range(24), (2,3,4))
print(B)
print(B +a)


tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]], shape=(2, 3, 4), dtype=int32)


In [26]:
print((B*a).shape)


(2, 3, 4)


In [27]:
x = tf.range(10, dtype=tf.float16)
print(x)
print(x.dtype)



tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float16)
<dtype: 'float16'>


In [30]:
tf.reduce_sum(x).shape

TensorShape([])

In [31]:
A.shape, tf.reduce_sum(A)

(TensorShape([5, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=190>)

In [43]:
print(A)
tf.reduce_sum(A, axis=0)
tf.reduce_sum(A, axis=1)
tf.reduce_sum(A, axis=0).shape
tf.reduce_sum(A, axis=1).shape

C = tf.reshape(tf.range(24), (2,3,4))
print(C)
print(tf.reduce_sum(C, axis=2))
print(tf.reduce_sum(C, axis=1))
print(tf.reduce_sum(C, axis=0))



tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[ 6 22 38]
 [54 70 86]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[12 15 18 21]
 [48 51 54 57]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]], shape=(3, 4), dtype=int32)


In [47]:
tf.reduce_sum(C, axis=[0,1])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([60, 66, 72, 78], dtype=int32)>

In [48]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [51]:
# Get size of tensor A and use it to create a new tensor
size = tf.size(A).numpy()
# Example 1: Create a zero tensor with same number of elements
zeros = tf.zeros(size)
print("Zero tensor:", zeros)

# Example 2: Create range tensor with same length
range_tensor = tf.range(size)
print("Range tensor:", range_tensor)

# Example 3: Use size in a condition
if size > 10:
    print("Tensor A has more than 10 elements")
else:
    print("Tensor A has 10 or fewer elements")



0