# 线性代数

In [2]:
import tensorflow as tf
x = tf.constant(3.0)
y = tf.constant(4.0)
print(x)
print(y)

print(x+y)
print(x*y)
print(x/y)
print(x**y)


tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(0.75, shape=(), dtype=float32)
tf.Tensor(81.0, shape=(), dtype=float32)


In [3]:
x = tf.range(10)
print(x)



tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [4]:
x[2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
len(x)

10

In [6]:
x.shape

TensorShape([10])

In [8]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
print(x.shape)
len(x)


[1 2 3 4 5]
(5,)


5

In [9]:
A = tf.reshape(tf.range(20), (5,4))
print(A)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)


In [10]:
print(A[2][3])

tf.Tensor(11, shape=(), dtype=int32)


In [12]:
AT = tf.transpose(A)
print(AT)

tf.Tensor(
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]], shape=(4, 5), dtype=int32)


In [13]:
B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B)

B == tf.transpose(B)

tf.Tensor(
[[1 2 3]
 [2 0 4]
 [3 4 5]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [14]:
X = tf.reshape(tf.range(24), (2,3,4))
print(X)


tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [15]:
A = tf.reshape(tf.range(20), (5,4))
B =A

In [16]:
id(A) == id(B)

True

In [17]:
A, A+B

(<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=int32)>,
 <tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]], dtype=int32)>)

In [18]:
A*B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]], dtype=int32)>

In [24]:
# tf.matmul(A, B)

a =2 
B = tf.reshape(tf.range(24), (2,3,4))
print(B)
print(B +a)


tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]], shape=(2, 3, 4), dtype=int32)


In [26]:
print((B*a).shape)


(2, 3, 4)


In [27]:
x = tf.range(10, dtype=tf.float16)
print(x)
print(x.dtype)



tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float16)
<dtype: 'float16'>


In [30]:
tf.reduce_sum(x).shape

TensorShape([])

In [31]:
A.shape, tf.reduce_sum(A)

(TensorShape([5, 4]), <tf.Tensor: shape=(), dtype=int32, numpy=190>)

In [43]:
print(A)
tf.reduce_sum(A, axis=0)
tf.reduce_sum(A, axis=1)
tf.reduce_sum(A, axis=0).shape
tf.reduce_sum(A, axis=1).shape

C = tf.reshape(tf.range(24), (2,3,4))
print(C)
print(tf.reduce_sum(C, axis=2))
print(tf.reduce_sum(C, axis=1))
print(tf.reduce_sum(C, axis=0))



tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[ 6 22 38]
 [54 70 86]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[12 15 18 21]
 [48 51 54 57]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]], shape=(3, 4), dtype=int32)


In [47]:
tf.reduce_sum(C, axis=[0,1])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([60, 66, 72, 78], dtype=int32)>

In [48]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [52]:
# Get size of tensor A and use it to create a new tensor
size = tf.size(A).numpy()
# Example 1: Create a zero tensor with same number of elements
zeros = tf.zeros(size)
print("Zero tensor:", zeros)

# Example 2: Create range tensor with same length
range_tensor = tf.range(size)
print("Range tensor:", range_tensor)

# Example 3: Use size in a condition
if size > 10:
    print("Tensor A has more than 10 elements")
else:
    print("Tensor A has 10 or fewer elements")



Zero tensor: tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(20,), dtype=float32)
Range tensor: tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], shape=(20,), dtype=int32)
Tensor A has more than 10 elements


In [57]:
print(A)
tf.reduce_mean(A, axis=0)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11], dtype=int32)>

In [58]:
A.shape
tf.reduce_sum(A, axis=0) / A.shape[0]


<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 8.,  9., 10., 11.])>

In [61]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
print(sum_A)

tf.Tensor(
[[ 6]
 [22]
 [38]
 [54]
 [70]], shape=(5, 1), dtype=int32)


In [63]:
print(A)
A / sum_A

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)


<tf.Tensor: shape=(5, 4), dtype=float64, numpy=
array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])>

In [70]:
print(A)
print(tf.cumsum(A))
print(tf.cumsum(A, axis=0))
tf.cumsum(A, axis=1)


tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]], shape=(5, 4), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]
 [40 45 50 55]], shape=(5, 4), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]
 [40 45 50 55]], shape=(5, 4), dtype=int32)


<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54],
       [16, 33, 51, 70]], dtype=int32)>

In [84]:
x=tf.range(4, dtype=tf.float32)
y= tf.ones(4, dtype=tf.float32)
print(x, y)
print(tf.matmul(tf.reshape(x, (1,4)), tf.reshape(y, (4,1))))
tf.tensordot(x, y, axes=1)


tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32) tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
tf.Tensor([[6.]], shape=(1, 1), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [86]:
# 矩阵乘法
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
matrix_product = tf.matmul(A, B)  # 或 A @ B
print(matrix_product)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [88]:
# 只适用于3D向量
x = tf.constant([1, 0, 0])  # i 方向单位向量
y = tf.constant([0, 1, 0])  # j 方向单位向量
cross_product = tf.linalg.cross(x, y)  # 结果是 k 方向单位向量 [0, 0, 1]
print(cross_product)

tf.Tensor([0 0 1], shape=(3,), dtype=int32)


In [95]:
A = tf.reshape(tf.range(20, dtype=tf.float32), (5,4))
print(A)
x = tf.range(4, dtype=tf.float32)
print(x)
A.shape, x.shape, tf.linalg.matvec(A, x)


tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]], shape=(5, 4), dtype=float32)
tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32)


(TensorShape([5, 4]),
 TensorShape([4]),
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>)

In [97]:
B = tf.ones((4, 3), dtype=tf.float32)
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]], dtype=float32)>

In [98]:
u = tf.constant([3.0, -4.0])
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [107]:
print(tf.reduce_sum(tf.abs(u)))
print(tf.norm(u, ord=1))

tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)


In [105]:
r = tf.Variable(tf.ones((4, 9)))
r = tf.tensor_scatter_nd_update(r, [[0,0], [1,1], [2,2], [3,3]], [3.0, 4.0, 5.0, 6.0])
print(r)
tf.norm(r, ord=1)



tf.Tensor(
[[3. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 4. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 6. 1. 1. 1. 1. 1.]], shape=(4, 9), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=50.0>