# 数据操作

In [2]:
import tensorflow as tf

In [4]:
x = tf.range(12)
x.shape

TensorShape([12])

In [5]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
x = tf.reshape(x, (4,3))

In [8]:
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [9]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [10]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [11]:
tf.random.normal(shape=[3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.5583387 , -0.12910604, -1.1686467 , -0.82112676],
       [ 0.9743943 , -1.2778778 , -0.184232  ,  0.951506  ],
       [-1.8130933 , -0.03175124, -2.011952  , -0.9749709 ]],
      dtype=float32)>

In [12]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [21]:
x = tf.constant([1.0,2,4,8])
y = tf.constant([2.0,2,2,2])
x+y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>

In [22]:
x*y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>

In [23]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809578e+03],
      dtype=float32)>

In [26]:
tf.matmul(tf.reshape(x,[1,4]), tf.reshape(y,[4,1]))


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[30.]], dtype=float32)>

In [3]:
X= tf.reshape(tf.range(12, dtype=tf.float32), (3,4))
Y =tf.constant([[2.0, 1, 4,3], [1, 2, 3, 4], [4, 3, 2, 1]])

tf.concat([X, Y], axis = 0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 2.,  1.,  4.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.]], dtype=float32)>

In [4]:
tf.concat([X, Y], axis = 1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>

In [26]:
print(X,Y)
X > Y

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32) tf.Tensor(
[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [6]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

In [7]:
a = tf.reshape(tf.range(3), (3,1))
b = tf.reshape(tf.range(2), (1,2))
a,b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [8]:
a+b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

In [14]:
print(X)
print("=======")
X[-1], X[2:3]

tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)


(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 8.,  9., 10., 11.]], dtype=float32)>)

In [16]:
X_var = tf.Variable(X)
print(X_var)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>


In [17]:
X_var[0:2, :].assign(tf.ones(X_var[0:2, :].shape, dtype=tf.float32)*2)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [18]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [19]:
Z = tf.Variable(tf.zeros_like(Y))
print(id(Z))
Z.assign(X + Y)
print(id(Z))

4582446208
4582446208


In [20]:
@tf.function
def computation(X, Y):
 Z = tf.zeros_like(Y)
 A = X+Y
 B=A+Y
 C=B+Y
 return C + Y
computation(X, Y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 8.,  9., 26., 27.],
       [24., 33., 42., 51.],
       [56., 57., 58., 59.]], dtype=float32)>

In [21]:
A = X.numpy()
B = tf.constant(A)
type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

In [22]:
a = tf.constant([3.5]).numpy()
a,a.item(), float(a), int(a)

/var/folders/gz/0gxv2qld2094b0b1mp3z79tc0000gn/T/ipykernel_20104/993293049.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a,a.item(), float(a), int(a)


(array([3.5], dtype=float32), 3.5, 3.5, 3)

In [42]:
tensor_3d = tf.zeros([3,1,2])
tensor_3d

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]], dtype=float32)>

In [29]:
a= tf.reshape(tf.range(3), (3,1))
a

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2]], dtype=int32)>

In [32]:
b=tf.reshape(tf.range(2), (1,2))
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>

In [34]:
import sys
list_example = [1, 2, 3]
tuple_example = (1, 2, 3)
print(sys.getsizeof(list_example))   # 更大
print(sys.getsizeof(tuple_example))  # 更小

88
64


In [35]:
a+b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

In [43]:
tensor_3d+tf.ones([1,2,2])

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>