# 线性回归简洁实现

In [2]:
%matplotlib inline
import torch
from d2l import torch as d2l
import numpy as np
from torch.utils import data

true_w = torch.tensor([2,-3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [6]:
def load_data(data_array, batch_size, is_train=True):
    """"构造数据"""
    dataset = data.TensorDataset(*data_array)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_data((features, labels), batch_size)


In [8]:
next(iter(data_iter))

[tensor([[-1.7873, -0.6008],
         [ 0.4659, -1.7651],
         [-0.6937,  0.7973],
         [ 1.7330, -0.1398],
         [ 0.1799,  0.2540],
         [ 0.3251,  1.2945],
         [ 0.7664,  0.6129],
         [ 0.4111, -0.2229],
         [ 0.3064,  0.8430],
         [-0.3823,  2.5962]]),
 tensor([[ 2.6776],
         [11.1168],
         [ 0.0946],
         [ 8.1443],
         [ 3.6851],
         [ 0.4424],
         [ 3.6502],
         [ 5.7943],
         [ 1.9506],
         [-5.3713]])]

In [10]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

In [11]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(1)

tensor([1.])

In [12]:
loss = nn.MSELoss()

In [13]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [18]:
num_epochs = 3
for i in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print("epoch:"+ str(i+1)+" loss:"+str(l))

epoch:1 loss:tensor(9.6174e-05, grad_fn=<MseLossBackward0>)
epoch:2 loss:tensor(9.6358e-05, grad_fn=<MseLossBackward0>)
epoch:3 loss:tensor(9.6974e-05, grad_fn=<MseLossBackward0>)


In [19]:
w = net[0].weight.data
b=net[0].bias.data
print(w,b)

tensor([[ 1.9986, -3.4002]]) tensor([4.2000])


In [1]:
# true_w = torch.tensor([2,-3.4])

print([0.0]*8)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [4]:
list(zip([1, 2, 3], ['a', 'b', 'c']))

[(1, 'a'), (2, 'b'), (3, 'c')]

In [5]:
a, *b, c = [1, 2, 3, 4, 5]
print(b)

[2, 3, 4]
