# 自定义层

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        
    def forward(self, X):
        return X -X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4]))

tensor([-1.5000, -0.5000,  0.5000,  1.5000])

In [4]:
net = nn.Sequential(
    nn.Linear(8,128),
    CenteredLayer()
)
Y = net(torch.rand(4,8))
Y.mean()

tensor(7.4506e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        # randn产生标准正态分布随机数，rand产生[0,1)均匀分布随机数
        self.bias = nn.Parameter(torch.rand(units,))  # 用rand代替randn
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 0.1225, -0.8731,  0.3074],
        [-0.2406,  0.3964,  0.6895],
        [ 1.5819,  0.2266,  0.1062],
        [-0.7759,  1.1614, -0.2788],
        [ 0.3383, -1.9589,  0.1050]], requires_grad=True)

In [8]:
linear(torch.randn(2,5))

tensor([[0.0000, 0.3524, 0.8142],
        [0.0000, 4.3127, 0.0000]])

In [9]:
net=nn.Sequential(
    MyLinear(64,8),
    MyLinear(8,1)
)

net(torch.rand(2,64))

tensor([[1.9365],
        [0.0000]])