# 概率

In [1]:
%matplotlib inline
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

/Users/haoyiwen/miniforge3/envs/d2l/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(


In [3]:
fair_probs = torch.ones([6]) / 6
print(fair_probs)

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])


In [5]:
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 0., 0., 0., 1.])

In [6]:
multinomial.Multinomial(10, fair_probs).sample()

tensor([1., 2., 3., 3., 0., 1.])

In [8]:
# 将结果存储为32位浮点数以进行除法
counts = multinomial.Multinomial(10000, fair_probs).sample()
counts / 10000  # 相对频率作为估计值

tensor([0.1694, 0.1648, 0.1655, 0.1619, 0.1616, 0.1768])

In [11]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))
print(counts, counts.shape)
cum_counts = counts.cumsum(dim=0)
print(cum_counts, cum_counts.shape)
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)
print(estimates, estimates.shape)

tensor([[2., 1., 1., 1., 1., 4.],
        [1., 3., 1., 2., 1., 2.],
        [0., 3., 2., 1., 2., 2.],
        ...,
        [1., 0., 3., 2., 3., 1.],
        [3., 2., 0., 1., 1., 3.],
        [0., 0., 1., 4., 4., 1.]]) torch.Size([500, 6])
tensor([[  2.,   1.,   1.,   1.,   1.,   4.],
        [  3.,   4.,   2.,   3.,   2.,   6.],
        [  3.,   7.,   4.,   4.,   4.,   8.],
        ...,
        [834., 831., 817., 834., 820., 844.],
        [837., 833., 817., 835., 821., 847.],
        [837., 833., 818., 839., 825., 848.]]) torch.Size([500, 6])
tensor([[0.2000, 0.1000, 0.1000, 0.1000, 0.1000, 0.4000],
        [0.1500, 0.2000, 0.1000, 0.1500, 0.1000, 0.3000],
        [0.1000, 0.2333, 0.1333, 0.1333, 0.1333, 0.2667],
        ...,
        [0.1675, 0.1669, 0.1641, 0.1675, 0.1647, 0.1695],
        [0.1677, 0.1669, 0.1637, 0.1673, 0.1645, 0.1697],
        [0.1674, 0.1666, 0.1636, 0.1678, 0.1650, 0.1696]]) torch.Size([500, 6])


In [12]:
counts = multinomial.Multinomial(10, fair_probs).sample((500,))
cum_counts = counts.cumsum(dim=0)
estimates = cum_counts / cum_counts.sum(dim=1, keepdims=True)

d2l.set_figsize((6, 4.5))
for i in range(6):
    d2l.plt.plot(estimates[:, i].numpy(),
                 label=("P(die=" + str(i + 1) + ")"))
d2l.plt.axhline(y=0.167, color='black', linestyle='dashed')
d2l.plt.gca().set_xlabel('Groups of experiments')
d2l.plt.gca().set_ylabel('Estimated probability')
d2l.plt.legend();

Error in callback <function _draw_all_if_interactive at 0x12f9645e0> (for post_execute), with arguments args (),kwargs {}:


ValueError: object __array__ method not producing an array

RecursionError: maximum recursion depth exceeded while calling a Python object

<Figure size 600x450 with 1 Axes>